#SPDX-License-Identifier: MIT-0
---
# tasks file for default_packages
- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: yes
  when: "inventory_hostname != ansible_hostname"

- name: Update /etc/hosts with the new hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname_short }} {{ inventory_hostname }}"
    state: present
  become: yes

- name: Package installation
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - "{{ packages_to_install }}"
