#SPDX-License-Identifier: MIT-0
---
# tasks file for proxy
- name: Install nginx
  apt:
    name: "nginx"
    state: present
  become: yes

- name: Change config
  ansible.builtin.template:
    src: index.j2
    dest: /etc/nginx/sites-available/default
  become: yes
  notify: "Nginx Reloader"
